### ISSUE TITLE
Printing Service downloaded instead of Chromecast Audio Stream

### ISSUE THREAD

**Issue by FA-Bubba** [acidhax/chromecast-audio-stream#121] opened 2019-01-02 20:04 UTC
I tried to download the Chromecasy-Audio-Stream App, but only get a Bonjour Print Services App.  Where is the AudioCast App?

**Comment by Flonja** [comment] 2019-01-06 12:56
Duplicate of #120

**Comment by FA-Bubba** [comment] 2019-01-06 14:51
I found newer version here:

https://github.com/SamDel/ChromeCast-Desktop-Audio-Streamer

**Closed as completed** 2019-01-06 14:50 UTC
